-- Isolerad testdatabas. Används bara av admin-elevroll.integration.js.
create role anon;
create role authenticated;
create schema auth;
create schema kg_private;
create table auth.users(id uuid primary key,email text,raw_user_meta_data jsonb);
create function auth.uid() returns uuid language sql stable as $f$
 select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid
$f$;
create function public.kg_ar_admin() returns boolean language sql stable as $f$
 select auth.uid()='00000000-0000-0000-0000-000000000001'::uuid
$f$;
create function kg_private.ar_larare(p_uid uuid) returns boolean language sql stable as $f$
 select p_uid in ('00000000-0000-0000-0000-000000000001'::uuid,'00000000-0000-0000-0000-000000000004'::uuid)
$f$;
create function public.ul_ar_larare() returns boolean language sql stable as $f$
 select kg_private.ar_larare(auth.uid())
$f$;
create function public.kg_ar_larare() returns boolean language sql stable as $f$
 select kg_private.ar_larare(auth.uid())
$f$;
create table public.kg_skola(id bigint generated by default as identity primary key,namn text,skapad_av uuid);
create unique index on public.kg_skola(lower(btrim(namn)));
create table kg_private.larprofil(user_id uuid primary key,namn text,skola_id bigint,aktiv boolean default true,skapad timestamptz default now(),andrad timestamptz default now());
create table kg_private.elevskola(user_id uuid primary key,skola_id bigint);
create table public.kg_grupp(id bigint primary key,namn text);
create table kg_private.grupplarare(grupp_id bigint,user_id uuid,primary key(grupp_id,user_id));
create table kg_private.gruppmedlem(grupp_id bigint,user_id uuid,primary key(grupp_id,user_id));
create table public.kg_klass(id bigint primary key,larare boolean);
create table kg_private.klassmedlem(user_id uuid primary key,klass_id bigint);
create table public.kg_provtraning(id bigint primary key,larare uuid,grupper bigint[]);
create table kg_private.provresultat(prov_id bigint,user_id uuid,klara integer);
create table kg_private.state(id uuid primary key,data jsonb);
create function kg_private.prov_larare() returns boolean language sql stable as $f$
 select coalesce(public.ul_ar_larare(),false) or coalesce(public.kg_ar_larare(),false) or coalesce(public.kg_ar_admin(),false)
 or exists(select 1 from kg_private.larprofil where user_id=auth.uid() and aktiv)
$f$;
create function kg_private.lar_har_grupp(p_grupp bigint) returns boolean language sql stable as $f$
 select auth.uid() is not null and (coalesce(public.kg_ar_admin(),false)
 or exists(select 1 from kg_private.grupplarare where user_id=auth.uid() and grupp_id=p_grupp))
$f$;
insert into auth.users select ('00000000-0000-0000-0000-'||lpad(n::text,12,'0'))::uuid,'test'||n||'@example.test','{}'::jsonb from generate_series(1,7) n;
insert into public.kg_skola(id,namn) values(1,'Skola A'),(2,'Skola B');
alter table public.kg_skola alter column id restart with 3;
insert into kg_private.larprofil(user_id,namn,skola_id,aktiv)
 select id,case when email='test2@example.test' then 'Elev Exempel' else 'Lärare Exempel' end,1,email<>'test5@example.test'
 from auth.users where email not in ('test3@example.test','test7@example.test');
insert into public.kg_grupp values(1,'Grupp Ett'),(2,'Grupp Två');
insert into kg_private.grupplarare select 1,id from auth.users where email in ('test2@example.test','test6@example.test');
insert into kg_private.gruppmedlem select case when email='test2@example.test' then 2 else 1 end,id from auth.users where email in ('test2@example.test','test3@example.test');
insert into public.kg_klass values(1,true),(2,false);
insert into kg_private.klassmedlem select id,case when email='test2@example.test' then 1 else 2 end from auth.users where email in ('test2@example.test','test5@example.test');
insert into kg_private.elevskola select id,2 from auth.users where email='test5@example.test';
insert into public.kg_provtraning select 1,id,array[1]::bigint[] from auth.users where email='test2@example.test';
insert into kg_private.provresultat select 1,id,7 from auth.users where email='test3@example.test';
insert into kg_private.state select id,'{"xp":500,"attempts":20,"courses":{"fy1":{"history":[{"id":"6.73a","ok":true}]}}}'::jsonb from auth.users;
