-- =====================================================================
-- Kunskapsgymmet: lärargrupper, elevstatistik och träningspass
-- Kräver att 2026-10-01-klasser.sql, 2026-10-01-egna-klasser.sql och
-- 2026-10-02-provtraning.sql redan är körda. Kör hela filen i Supabase →
-- SQL Editor. Den kan köras om utan skada.
--
--   * public.kg_grupp             lärarens grupper (undervisningsgrupper)
--   * kg_private.grupplarare      vilka lärare som har en grupp (flera går)
--   * kg_private.gruppmedlem      elever i gruppen (en elev kan ha flera)
--   * kg_private.provdold         träningspass som en elev har dolt för sig
--   * kg_provtraning.grupper      vilka grupper ett träningspass riktas till
--
-- Topplistans klasser (kg_klass) påverkas inte. Lärare kan bara se elever
-- som själva gått med i lärarens grupp med kod eller länk, eller som admin
-- har flyttat över från en befintlig klass.
--
-- Elev:   kg_anslut_kod(p_kod), kg_mina_grupper(), kg_grupp_lamna(p_grupp),
--         kg_prov_dolj(p_prov)
-- Lärare: kg_lar_grupper(), kg_lar_grupp_skapa(p_namn),
--         kg_lar_grupp_andra(p_grupp,p_namn), kg_lar_grupp_ta_bort(p_grupp),
--         kg_lar_kollega(p_grupp,p_epost), kg_lar_ta_bort_elev(p_grupp,p_user),
--         kg_lar_elever(p_grupp), kg_lar_elev(p_grupp,p_user),
--         kg_lar_grupp_omraden(p_grupp,p_kurs), kg_prov_ta_bort(p_prov)
-- Admin:  kg_admin_grupp_fran_klass(p_klass,p_epost)
-- Global statistik (kg_statistik) blir bara tillgänglig för admin.
-- =====================================================================

begin;

create table if not exists public.kg_grupp (
  id         bigint generated by default as identity primary key,
  namn       text not null check (char_length(btrim(namn)) between 2 and 40),
  kod        text not null,
  skapad_av  uuid not null,
  skapad     timestamptz not null default now()
);
create unique index if not exists kg_grupp_kod_uk on public.kg_grupp (upper(kod));
alter table public.kg_grupp enable row level security;   -- inga policys: all åtkomst via funktionerna

create table if not exists kg_private.grupplarare (
  grupp_id  bigint not null references public.kg_grupp(id) on delete cascade,
  user_id   uuid not null,
  satt      timestamptz not null default now(),
  primary key (grupp_id, user_id)
);
create index if not exists grupplarare_user_idx on kg_private.grupplarare (user_id);

create table if not exists kg_private.gruppmedlem (
  grupp_id  bigint not null references public.kg_grupp(id) on delete cascade,
  user_id   uuid not null,
  gick_med  timestamptz not null default now(),
  primary key (grupp_id, user_id)
);
create index if not exists gruppmedlem_user_idx on kg_private.gruppmedlem (user_id);

create table if not exists kg_private.provdold (
  prov_id  bigint not null references public.kg_provtraning(id) on delete cascade,
  user_id  uuid not null,
  dold     timestamptz not null default now(),
  primary key (prov_id, user_id)
);

alter table public.kg_provtraning add column if not exists grupper bigint[] not null default '{}';

-- ---------------------------------------------------------------------
-- Hjälpfunktioner
CREATE OR REPLACE FUNCTION kg_private.anv_namn(p_uid uuid)
 RETURNS text
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO ''
AS $function$
  select coalesce(nullif(btrim(u.raw_user_meta_data->>'full_name'),''),
                  nullif(btrim(u.raw_user_meta_data->>'name'),''),
                  split_part(u.email,'@',1))
    from auth.users u where u.id = p_uid
$function$;

CREATE OR REPLACE FUNCTION kg_private.lar_har_grupp(p_grupp bigint)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO ''
AS $function$
  select auth.uid() is not null and (
    exists (select 1 from kg_private.grupplarare l where l.grupp_id = p_grupp and l.user_id = auth.uid())
    or coalesce(public.kg_ar_admin(),false))
$function$;

-- Sex tecken utan förväxlingsbara tecken (0/O, 1/I/L). Unik mot både
-- grupper och träningspass, eftersom eleven skriver in samma sorts kod.
CREATE OR REPLACE FUNCTION kg_private.ny_kod()
 RETURNS text
 LANGUAGE plpgsql
 VOLATILE SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare tecken text := 'ABCDEFGHJKMNPQRSTUVWXYZ23456789'; v text; i int;
begin
  loop
    v := '';
    for i in 1..6 loop
      v := v || substr(tecken, 1 + floor(random()*length(tecken))::int, 1);
    end loop;
    exit when not exists (select 1 from public.kg_grupp where upper(kod) = v)
          and not exists (select 1 from public.kg_provtraning where upper(kod) = v);
  end loop;
  return v;
end $function$;

-- Ett försök ur elevens historik som rad: kurs, område, rätt och tidpunkt.
CREATE OR REPLACE FUNCTION kg_private.elev_forsok(p_uid uuid)
 RETURNS TABLE(kurs text, omr text, ok boolean, tid timestamptz)
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO ''
AS $function$
  select c.key, h->>'area', coalesce((h->>'ok')::boolean,false),
         to_timestamp(((h->>'at')::numeric)/1000.0)
    from kg_private.state s,
         jsonb_each(case when jsonb_typeof(s.data->'courses')='object' then s.data->'courses' else '{}'::jsonb end) c,
         jsonb_array_elements(case when jsonb_typeof(c.value->'history')='array' then c.value->'history' else '[]'::jsonb end) h
   where s.id = p_uid and c.key <> 'none' and (h->>'at') ~ '^[0-9]+(\.[0-9]+)?$'
$function$;

-- ---------------------------------------------------------------------
-- Elev: gå med med kod. Koden kan vara en grupps eller ett träningspass.
CREATE OR REPLACE FUNCTION public.kg_anslut_kod(p_kod text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare uid uuid := auth.uid(); g public.kg_grupp%rowtype; p public.kg_provtraning%rowtype; v_kod text;
begin
  if uid is null then return jsonb_build_object('ok',false,'code','ej_inloggad'); end if;
  v_kod := upper(btrim(coalesce(p_kod,'')));
  select * into g from public.kg_grupp where upper(kod) = v_kod;
  if found then
    insert into kg_private.gruppmedlem(grupp_id,user_id) values (g.id, uid) on conflict do nothing;
    return jsonb_build_object('ok',true,'typ','grupp','grupp',jsonb_build_object('id',g.id,'namn',g.namn,
      'larare',(select coalesce(jsonb_agg(kg_private.anv_namn(l.user_id) order by l.satt),'[]'::jsonb)
                  from kg_private.grupplarare l where l.grupp_id = g.id)));
  end if;
  select * into p from public.kg_provtraning where upper(kod) = v_kod and aktiv;
  if found then
    insert into kg_private.provdeltagare(prov_id,user_id) values (p.id, uid) on conflict do nothing;
    delete from kg_private.provdold where prov_id = p.id and user_id = uid;
    return jsonb_build_object('ok',true,'typ','prov','prov',kg_private.prov_json(p, uid));
  end if;
  return jsonb_build_object('ok',false,'code','okand');
end $function$;

CREATE OR REPLACE FUNCTION public.kg_mina_grupper()
 RETURNS jsonb
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO ''
AS $function$
  select coalesce(jsonb_agg(jsonb_build_object('id',g.id,'namn',g.namn,
           'larare',(select coalesce(jsonb_agg(kg_private.anv_namn(l.user_id) order by l.satt),'[]'::jsonb)
                       from kg_private.grupplarare l where l.grupp_id = g.id))
         order by m.gick_med), '[]'::jsonb)
    from kg_private.gruppmedlem m join public.kg_grupp g on g.id = m.grupp_id
   where m.user_id = auth.uid()
$function$;

CREATE OR REPLACE FUNCTION public.kg_grupp_lamna(p_grupp bigint)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
begin
  if auth.uid() is null then return jsonb_build_object('ok',false,'code','ej_inloggad'); end if;
  delete from kg_private.gruppmedlem where grupp_id = p_grupp and user_id = auth.uid();
  return jsonb_build_object('ok',true);
end $function$;

-- Eleven döljer ett träningspass permanent för sig själv. Resultaten finns kvar för läraren.
CREATE OR REPLACE FUNCTION public.kg_prov_dolj(p_prov bigint)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
begin
  if auth.uid() is null then return jsonb_build_object('ok',false,'code','ej_inloggad'); end if;
  if not exists (select 1 from public.kg_provtraning where id = p_prov) then
    return jsonb_build_object('ok',false,'code','okand');
  end if;
  insert into kg_private.provdold(prov_id,user_id) values (p_prov, auth.uid()) on conflict do nothing;
  return jsonb_build_object('ok',true);
end $function$;

-- ---------------------------------------------------------------------
-- Lärare: grupper
CREATE OR REPLACE FUNCTION public.kg_lar_grupper()
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare uid uuid := auth.uid();
begin
  if uid is null or not kg_private.prov_larare() then return jsonb_build_object('ok',false,'code','larare_kravs'); end if;
  return jsonb_build_object('ok',true,'grupper',coalesce((
    select jsonb_agg(jsonb_build_object(
             'id',g.id,'namn',g.namn,'kod',g.kod,'skapad',g.skapad,'egen',g.skapad_av = uid,
             'elever',(select count(*) from kg_private.gruppmedlem m where m.grupp_id = g.id),
             'aktiva',(select count(distinct m.user_id) from kg_private.gruppmedlem m
                        where m.grupp_id = g.id
                          and exists (select 1 from kg_private.elev_forsok(m.user_id) f
                                       where f.tid > now() - interval '7 days')),
             'larare',(select coalesce(jsonb_agg(kg_private.anv_namn(l.user_id) order by l.satt),'[]'::jsonb)
                         from kg_private.grupplarare l where l.grupp_id = g.id))
           order by g.namn)
      from public.kg_grupp g
     where exists (select 1 from kg_private.grupplarare l where l.grupp_id = g.id and l.user_id = uid)),
    '[]'::jsonb));
end $function$;

CREATE OR REPLACE FUNCTION public.kg_lar_grupp_skapa(p_namn text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare uid uuid := auth.uid(); v_namn text; v_id bigint; v_kod text;
begin
  if uid is null or not kg_private.prov_larare() then return jsonb_build_object('ok',false,'code','larare_kravs'); end if;
  v_namn := regexp_replace(btrim(coalesce(p_namn,'')), '\s+', ' ', 'g');
  if char_length(v_namn) not between 2 and 40 then return jsonb_build_object('ok',false,'code','namn'); end if;
  if (select count(*) from public.kg_grupp where skapad_av = uid and skapad > now() - interval '1 day') >= 30 then
    return jsonb_build_object('ok',false,'code','for_manga');
  end if;
  v_kod := kg_private.ny_kod();
  insert into public.kg_grupp(namn,kod,skapad_av) values (v_namn, v_kod, uid) returning id into v_id;
  insert into kg_private.grupplarare(grupp_id,user_id) values (v_id, uid);
  return jsonb_build_object('ok',true,'id',v_id,'kod',v_kod,'namn',v_namn);
end $function$;

CREATE OR REPLACE FUNCTION public.kg_lar_grupp_andra(p_grupp bigint, p_namn text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare v_namn text;
begin
  if not kg_private.lar_har_grupp(p_grupp) then return jsonb_build_object('ok',false,'code','larare_kravs'); end if;
  v_namn := regexp_replace(btrim(coalesce(p_namn,'')), '\s+', ' ', 'g');
  if char_length(v_namn) not between 2 and 40 then return jsonb_build_object('ok',false,'code','namn'); end if;
  update public.kg_grupp set namn = v_namn where id = p_grupp;
  return jsonb_build_object('ok',true);
end $function$;

-- Hela gruppen tas bort för alla lärare. Elevernas egen träning påverkas inte.
CREATE OR REPLACE FUNCTION public.kg_lar_grupp_ta_bort(p_grupp bigint)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
begin
  if not kg_private.lar_har_grupp(p_grupp) then return jsonb_build_object('ok',false,'code','larare_kravs'); end if;
  update public.kg_provtraning set grupper = array_remove(grupper, p_grupp) where p_grupp = any(grupper);
  delete from public.kg_grupp where id = p_grupp;
  return jsonb_build_object('ok',true);
end $function$;

-- Lägg till en kollega med e-post. Kontot måste vara ett godkänt lärarkonto.
CREATE OR REPLACE FUNCTION public.kg_lar_kollega(p_grupp bigint, p_epost text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare v_uid uuid;
begin
  if not kg_private.lar_har_grupp(p_grupp) then return jsonb_build_object('ok',false,'code','larare_kravs'); end if;
  select id into v_uid from auth.users where lower(btrim(email)) = lower(btrim(coalesce(p_epost,''))) limit 1;
  if v_uid is null then return jsonb_build_object('ok',false,'code','okant_konto'); end if;
  if not kg_private.ar_larare(v_uid) then return jsonb_build_object('ok',false,'code','ej_larare'); end if;
  insert into kg_private.grupplarare(grupp_id,user_id) values (p_grupp, v_uid) on conflict do nothing;
  return jsonb_build_object('ok',true,'namn',kg_private.anv_namn(v_uid));
end $function$;

CREATE OR REPLACE FUNCTION public.kg_lar_ta_bort_elev(p_grupp bigint, p_user uuid)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
begin
  if not kg_private.lar_har_grupp(p_grupp) then return jsonb_build_object('ok',false,'code','larare_kravs'); end if;
  delete from kg_private.gruppmedlem where grupp_id = p_grupp and user_id = p_user;
  return jsonb_build_object('ok',true);
end $function$;

-- ---------------------------------------------------------------------
-- Lärare: statistik. Läraren får sammanställda siffror, aldrig elevens profil.
CREATE OR REPLACE FUNCTION public.kg_lar_elever(p_grupp bigint)
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO ''
AS $function$
begin
  if not kg_private.lar_har_grupp(p_grupp) then return jsonb_build_object('ok',false,'code','larare_kravs'); end if;
  return jsonb_build_object('ok',true,'elever',coalesce((
    select jsonb_agg(x order by x->>'namn')
      from (
        select jsonb_build_object(
                 'id',m.user_id,
                 'namn',kg_private.anv_namn(m.user_id),
                 'epost',(select u.email from auth.users u where u.id = m.user_id),
                 'xp',coalesce((s.data->>'xp')::bigint,0),
                 'uppgifter',coalesce((s.data->>'attempts')::bigint,0),
                 'vecka',(select count(*) from kg_private.elev_forsok(m.user_id) f where f.tid > now() - interval '7 days'),
                 'vecka_ratt',(select count(*) from kg_private.elev_forsok(m.user_id) f where f.tid > now() - interval '7 days' and f.ok),
                 'senaste',(select count(*) from kg_private.elev_forsok(m.user_id) f),
                 'senaste_ratt',(select count(*) from kg_private.elev_forsok(m.user_id) f where f.ok),
                 'senast',(select max(f.tid) from kg_private.elev_forsok(m.user_id) f),
                 'gick_med',m.gick_med) as x
          from kg_private.gruppmedlem m
          left join kg_private.state s on s.id = m.user_id
         where m.grupp_id = p_grupp
      ) e), '[]'::jsonb));
end $function$;

CREATE OR REPLACE FUNCTION public.kg_lar_elev(p_grupp bigint, p_user uuid)
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare s kg_private.state%rowtype; v_kurser jsonb; v_dagar jsonb; v_pass jsonb;
begin
  if not kg_private.lar_har_grupp(p_grupp) then return jsonb_build_object('ok',false,'code','larare_kravs'); end if;
  if not exists (select 1 from kg_private.gruppmedlem where grupp_id = p_grupp and user_id = p_user) then
    return jsonb_build_object('ok',false,'code','ej_medlem');
  end if;
  select * into s from kg_private.state where id = p_user;

  -- Per kurs: försök i historiken och behärskning per område.
  select coalesce(jsonb_agg(k order by (k->>'senast') desc nulls last), '[]'::jsonb) into v_kurser
    from (
      select jsonb_build_object(
               'kurs',c.key,
               'forsok',(select count(*) from kg_private.elev_forsok(p_user) f where f.kurs = c.key),
               'ratt',(select count(*) from kg_private.elev_forsok(p_user) f where f.kurs = c.key and f.ok),
               'vecka',(select count(*) from kg_private.elev_forsok(p_user) f where f.kurs = c.key and f.tid > now() - interval '7 days'),
               'senast',(select max(f.tid) from kg_private.elev_forsok(p_user) f where f.kurs = c.key),
               'omraden',(
                 select coalesce(jsonb_agg(jsonb_build_object(
                          'omr',a.key,
                          'm',round((a.value)::numeric,3),
                          'f',(select count(*) from kg_private.elev_forsok(p_user) f where f.kurs = c.key and f.omr = a.key),
                          'r',(select count(*) from kg_private.elev_forsok(p_user) f where f.kurs = c.key and f.omr = a.key and f.ok))
                        order by (a.value)::numeric), '[]'::jsonb)
                   from jsonb_each(case when jsonb_typeof(c.value->'areas')='object' then c.value->'areas' else '{}'::jsonb end) a
                  where jsonb_typeof(a.value) = 'number')) as k
        from jsonb_each(case when jsonb_typeof(s.data->'courses')='object' then s.data->'courses' else '{}'::jsonb end) c
       where c.key <> 'none'
    ) x;

  -- Antal uppgifter per dag de senaste 14 dagarna (svensk tid).
  select coalesce(jsonb_object_agg(d, n), '{}'::jsonb) into v_dagar
    from (select to_char(f.tid at time zone 'Europe/Stockholm','YYYY-MM-DD') d, count(*) n
            from kg_private.elev_forsok(p_user) f
           where f.tid > now() - interval '14 days'
           group by 1) y;

  -- Träningspass i gruppen eller där eleven har resultat hos den här läraren.
  select coalesce(jsonb_agg(jsonb_build_object('id',p.id,'titel',p.titel,'kurs',p.kurs,'antal',p.antal,
           'klara',coalesce(r.klara,0),'ratt',coalesce(r.ratt,0),'aktiv',p.aktiv) order by p.skapad desc), '[]'::jsonb)
    into v_pass
    from public.kg_provtraning p
    left join kg_private.provresultat r on r.prov_id = p.id and r.user_id = p_user
   where p_grupp = any(p.grupper) or (r.user_id is not null and p.larare = auth.uid());

  return jsonb_build_object('ok',true,
    'namn',kg_private.anv_namn(p_user),
    'epost',(select u.email from auth.users u where u.id = p_user),
    'xp',coalesce((s.data->>'xp')::bigint,0),
    'uppgifter',coalesce((s.data->>'attempts')::bigint,0),
    'streak',coalesce((s.data->>'streak')::int,0),
    'kurser',v_kurser,'dagar',v_dagar,'pass',v_pass);
end $function$;

-- Gruppens svagaste och starkaste områden i en kurs.
CREATE OR REPLACE FUNCTION public.kg_lar_grupp_omraden(p_grupp bigint, p_kurs text)
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO ''
AS $function$
begin
  if not kg_private.lar_har_grupp(p_grupp) then return jsonb_build_object('ok',false,'code','larare_kravs'); end if;
  return jsonb_build_object('ok',true,'omraden',coalesce((
    select jsonb_object_agg(omr, jsonb_build_object('elever',elever,'m',m,'forsok',forsok,'ratt',ratt))
      from (
        select a.key as omr, count(*) as elever, round(avg((a.value)::numeric),3) as m,
               sum((select count(*) from kg_private.elev_forsok(mm.user_id) f where f.kurs = p_kurs and f.omr = a.key)) as forsok,
               sum((select count(*) from kg_private.elev_forsok(mm.user_id) f where f.kurs = p_kurs and f.omr = a.key and f.ok)) as ratt
          from kg_private.gruppmedlem mm
          join kg_private.state s on s.id = mm.user_id,
               jsonb_each(case when jsonb_typeof(s.data->'courses'->p_kurs->'areas')='object'
                               then s.data->'courses'->p_kurs->'areas' else '{}'::jsonb end) a
         where mm.grupp_id = p_grupp and jsonb_typeof(a.value) = 'number'
         group by a.key
      ) z), '{}'::jsonb));
end $function$;

-- ---------------------------------------------------------------------
-- Admin: gör en befintlig topplisteklass till en lärargrupp med samma elever.
CREATE OR REPLACE FUNCTION public.kg_admin_grupp_fran_klass(p_klass bigint, p_epost text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare k public.kg_klass%rowtype; v_uid uuid; v_id bigint; v_kod text; v_n int;
begin
  if not coalesce(public.kg_ar_admin(),false) then return jsonb_build_object('ok',false,'code','admin_kravs'); end if;
  select * into k from public.kg_klass where id = p_klass;
  if not found or k.larare then return jsonb_build_object('ok',false,'code','okand_klass'); end if;
  select id into v_uid from auth.users where lower(btrim(email)) = lower(btrim(coalesce(p_epost,''))) limit 1;
  if v_uid is null then return jsonb_build_object('ok',false,'code','okant_konto'); end if;
  if not kg_private.ar_larare(v_uid) then return jsonb_build_object('ok',false,'code','ej_larare'); end if;
  v_kod := kg_private.ny_kod();
  insert into public.kg_grupp(namn,kod,skapad_av) values (left(k.namn,40), v_kod, v_uid) returning id into v_id;
  insert into kg_private.grupplarare(grupp_id,user_id) values (v_id, v_uid);
  insert into kg_private.gruppmedlem(grupp_id,user_id)
  select v_id, m.user_id from kg_private.klassmedlem m
   where m.klass_id = p_klass and not kg_private.ar_larare(m.user_id)
  on conflict do nothing;
  get diagnostics v_n = row_count;
  return jsonb_build_object('ok',true,'id',v_id,'kod',v_kod,'elever',v_n,'larare',kg_private.anv_namn(v_uid));
end $function$;

-- ---------------------------------------------------------------------
-- Träningspass riktade till lärarens grupper
CREATE OR REPLACE FUNCTION kg_private.prov_lar_kan(p public.kg_provtraning)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO ''
AS $function$
  select auth.uid() is not null and (
    p.larare = auth.uid()
    or coalesce(public.kg_ar_admin(),false)
    or exists (select 1 from kg_private.grupplarare l where l.user_id = auth.uid() and l.grupp_id = any(p.grupper)))
$function$;

CREATE OR REPLACE FUNCTION kg_private.prov_elev_kan(p public.kg_provtraning, p_uid uuid)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO ''
AS $function$
  select exists (select 1 from kg_private.klassmedlem m where m.user_id = p_uid and m.klass_id = p.klass_id)
      or exists (select 1 from kg_private.provdeltagare d where d.user_id = p_uid and d.prov_id = p.id)
      or exists (select 1 from kg_private.gruppmedlem g where g.user_id = p_uid and g.grupp_id = any(p.grupper))
$function$;

drop function if exists public.kg_prov_skapa(text,text,text,text[],text[],integer,date,bigint,text);
CREATE OR REPLACE FUNCTION public.kg_prov_skapa(
  p_titel text, p_kurs text, p_spar text, p_omraden text[], p_nivaer text[],
  p_antal integer, p_datum date, p_grupper bigint[], p_kod text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare uid uuid := auth.uid(); v_kod text; v_bas text; n int := 1; v_id bigint; v_titel text; g bigint;
begin
  if uid is null then return jsonb_build_object('ok',false,'code','ej_inloggad'); end if;
  if not kg_private.prov_larare() then return jsonb_build_object('ok',false,'code','larare_kravs'); end if;
  v_titel := regexp_replace(btrim(coalesce(p_titel,'')), '\s+', ' ', 'g');
  if char_length(v_titel) not between 2 and 60 then return jsonb_build_object('ok',false,'code','titel'); end if;
  if coalesce(cardinality(p_omraden),0) = 0 then return jsonb_build_object('ok',false,'code','omraden'); end if;
  if coalesce(cardinality(p_nivaer),0) = 0 or not (p_nivaer <@ array['E','C','A']) then
    return jsonb_build_object('ok',false,'code','nivaer');
  end if;
  if p_antal is null or p_antal not between 5 and 100 then return jsonb_build_object('ok',false,'code','antal'); end if;
  foreach g in array coalesce(p_grupper,'{}') loop
    if not kg_private.lar_har_grupp(g) then return jsonb_build_object('ok',false,'code','okand_grupp'); end if;
  end loop;
  v_bas := upper(regexp_replace(coalesce(nullif(btrim(p_kod),''),v_titel), '[^A-Za-z0-9ÅÄÖåäö-]+', '-', 'g'));
  v_bas := translate(v_bas, 'ÅÄÖ', 'AAO');
  v_bas := btrim(left(regexp_replace(v_bas, '-{2,}', '-', 'g'), 24), '-');
  if char_length(v_bas) < 3 then v_bas := 'PASS-' || to_char(now(),'YYMMDD'); end if;
  v_kod := v_bas;
  while exists (select 1 from public.kg_provtraning where upper(kod) = upper(v_kod))
     or exists (select 1 from public.kg_grupp where upper(kod) = upper(v_kod)) loop
    n := n + 1; v_kod := v_bas || '-' || n;
  end loop;
  insert into public.kg_provtraning(kod,titel,kurs,spar,omraden,nivaer,antal,datum,klass_id,larare,grupper)
  values (v_kod, v_titel, lower(p_kurs), nullif(lower(btrim(coalesce(p_spar,''))),''), p_omraden, p_nivaer,
          p_antal, p_datum, null, uid, coalesce(p_grupper,'{}'))
  returning id into v_id;
  return jsonb_build_object('ok',true,'id',v_id,'kod',v_kod);
end $function$;

CREATE OR REPLACE FUNCTION public.kg_prov_mina()
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare uid uuid := auth.uid();
begin
  if uid is null or not kg_private.prov_larare() then return jsonb_build_object('ok',false,'code','larare_kravs'); end if;
  return jsonb_build_object('ok',true,'prov',coalesce((
    select jsonb_agg(kg_private.prov_json(p, uid) || jsonb_build_object(
             'tranat',(select count(*) from kg_private.provresultat r where r.prov_id=p.id and r.klara>0),
             'egen',p.larare = uid,
             'grupper',(select coalesce(jsonb_agg(jsonb_build_object('id',g.id,'namn',g.namn) order by g.namn),'[]'::jsonb)
                          from public.kg_grupp g where g.id = any(p.grupper)))
           order by p.aktiv desc, p.skapad desc)
      from public.kg_provtraning p
     where p.larare = uid
        or exists (select 1 from kg_private.grupplarare l where l.user_id = uid and l.grupp_id = any(p.grupper))),
    '[]'::jsonb));
end $function$;

CREATE OR REPLACE FUNCTION public.kg_prov_sammanstallning(p_prov bigint)
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare uid uuid := auth.uid(); p public.kg_provtraning%rowtype; v_elever int; v_tranat int; v_omr jsonb; v_klara int; v_lista jsonb;
begin
  if uid is null then return jsonb_build_object('ok',false,'code','ej_inloggad'); end if;
  select * into p from public.kg_provtraning where id = p_prov;
  if not found then return jsonb_build_object('ok',false,'code','okand'); end if;
  if not kg_private.prov_lar_kan(p) then return jsonb_build_object('ok',false,'code','larare_kravs'); end if;
  with elever as (
    select m.user_id from kg_private.klassmedlem m
      join public.kg_klass k on k.id = m.klass_id
     where p.klass_id is not null and m.klass_id = p.klass_id and not k.larare
    union select d.user_id from kg_private.provdeltagare d where d.prov_id = p.id
    union select r.user_id from kg_private.provresultat r where r.prov_id = p.id
    union select g.user_id from kg_private.gruppmedlem g where g.grupp_id = any(p.grupper)
  )
  select count(*), coalesce(jsonb_agg(jsonb_build_object(
           'id',e.user_id,'namn',kg_private.anv_namn(e.user_id),
           'klara',coalesce(r.klara,0),'ratt',coalesce(r.ratt,0),
           'dold',exists (select 1 from kg_private.provdold d where d.prov_id = p.id and d.user_id = e.user_id))
         order by kg_private.anv_namn(e.user_id)), '[]'::jsonb)
    into v_elever, v_lista
    from elever e left join kg_private.provresultat r on r.prov_id = p.id and r.user_id = e.user_id;
  select count(*), coalesce(sum(klara),0) into v_tranat, v_klara
    from kg_private.provresultat where prov_id = p.id and klara > 0;
  select coalesce(jsonb_object_agg(o, jsonb_build_object('forsok',f,'ratt',r,'elever',e)), '{}'::jsonb) into v_omr
    from (
      select o.key as o,
             sum(coalesce((o.value->>'f')::int,0)) as f,
             sum(coalesce((o.value->>'r')::int,0)) as r,
             count(*) filter (where coalesce((o.value->>'f')::int,0) > 0) as e
        from kg_private.provresultat res, jsonb_each(res.per_omr) o
       where res.prov_id = p.id
       group by o.key
    ) x;
  return jsonb_build_object('ok',true,'elever',v_elever,'tranat',v_tranat,'uppgifter',v_klara,
                            'omraden',v_omr,'elevlista',v_lista,'prov',kg_private.prov_json(p, uid));
end $function$;

CREATE OR REPLACE FUNCTION public.kg_prov_avsluta(p_prov bigint, p_aktiv boolean DEFAULT false)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare p public.kg_provtraning%rowtype;
begin
  select * into p from public.kg_provtraning where id = p_prov;
  if not found or not kg_private.prov_lar_kan(p) then return jsonb_build_object('ok',false,'code','okand'); end if;
  update public.kg_provtraning set aktiv = coalesce(p_aktiv,false) where id = p_prov;
  return jsonb_build_object('ok',true);
end $function$;

-- Läraren raderar passet permanent, inklusive elevernas resultat i passet.
CREATE OR REPLACE FUNCTION public.kg_prov_ta_bort(p_prov bigint)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare p public.kg_provtraning%rowtype;
begin
  select * into p from public.kg_provtraning where id = p_prov;
  if not found or not kg_private.prov_lar_kan(p) then return jsonb_build_object('ok',false,'code','okand'); end if;
  delete from public.kg_provtraning where id = p_prov;
  return jsonb_build_object('ok',true);
end $function$;

CREATE OR REPLACE FUNCTION public.kg_prov_for_mig()
 RETURNS jsonb
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO ''
AS $function$
  select coalesce(jsonb_agg(kg_private.prov_json(p, auth.uid()) order by p.datum nulls last, p.id), '[]'::jsonb)
    from public.kg_provtraning p
   where auth.uid() is not null and p.aktiv
     and (p.datum is null or p.datum >= ((now() at time zone 'Europe/Stockholm')::date - 1))
     and kg_private.prov_elev_kan(p, auth.uid())
     and not exists (select 1 from kg_private.provdold d where d.prov_id = p.id and d.user_id = auth.uid())
$function$;

CREATE OR REPLACE FUNCTION public.kg_prov_rapportera(p_prov bigint, p_klara integer, p_ratt integer, p_omr jsonb)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare uid uuid := auth.uid(); p public.kg_provtraning%rowtype; v_omr jsonb := '{}'::jsonb; o record;
begin
  if uid is null then return jsonb_build_object('ok',false,'code','ej_inloggad'); end if;
  select * into p from public.kg_provtraning where id = p_prov;
  if not found then return jsonb_build_object('ok',false,'code','okand'); end if;
  if not kg_private.prov_elev_kan(p, uid) then return jsonb_build_object('ok',false,'code','ej_deltagare'); end if;
  if jsonb_typeof(p_omr) = 'object' then
    for o in select key, value from jsonb_each(p_omr) loop
      if o.key = any(p.omraden) and jsonb_typeof(o.value) = 'object' then
        v_omr := v_omr || jsonb_build_object(o.key, jsonb_build_object(
          'f', least(greatest(coalesce((o.value->>'f')::int,0),0),1000),
          'r', least(greatest(coalesce((o.value->>'r')::int,0),0),1000)));
      end if;
    end loop;
  end if;
  insert into kg_private.provresultat(prov_id,user_id,klara,ratt,per_omr,uppdaterad)
  values (p.id, uid, least(greatest(coalesce(p_klara,0),0),1000), least(greatest(coalesce(p_ratt,0),0),1000), v_omr, now())
  on conflict (prov_id,user_id) do update
    set klara = greatest(kg_private.provresultat.klara, excluded.klara),
        ratt = greatest(kg_private.provresultat.ratt, excluded.ratt),
        per_omr = excluded.per_omr,
        uppdaterad = now();
  return jsonb_build_object('ok',true);
end $function$;

-- ---------------------------------------------------------------------
-- Global statistik: bara admin. Den befintliga funktionen döps om och
-- ersätts av en spärr som anropar den. Körs bara en gång.
do $do$
declare v_ret text; v_kropp text;
begin
  if to_regprocedure('public.kg_statistik()') is not null
     and to_regprocedure('kg_private.kg_statistik_intern()') is null then
    select pg_catalog.pg_get_function_result('public.kg_statistik()'::regprocedure) into v_ret;
    alter function public.kg_statistik() set schema kg_private;
    alter function kg_private.kg_statistik() rename to kg_statistik_intern;
    revoke all on function kg_private.kg_statistik_intern() from public, anon, authenticated;
    v_kropp := case when v_ret ilike 'TABLE(%' or v_ret ilike 'SETOF %'
                    then 'return query select * from kg_private.kg_statistik_intern();'
                    else 'return kg_private.kg_statistik_intern();' end;
    execute format($f$
      create function public.kg_statistik() returns %s
      language plpgsql security definer set search_path to ''
      as $b$
      begin
        if not coalesce(public.kg_ar_admin(),false) then
          raise exception 'Bara admin' using errcode = '42501';
        end if;
        %s
      end $b$;$f$, v_ret, v_kropp);
    revoke all on function public.kg_statistik() from public, anon;
    grant execute on function public.kg_statistik() to authenticated;
  end if;
end $do$;

-- ---------------------------------------------------------------------
revoke all on function public.kg_anslut_kod(text) from public, anon;
revoke all on function public.kg_mina_grupper() from public, anon;
revoke all on function public.kg_grupp_lamna(bigint) from public, anon;
revoke all on function public.kg_prov_dolj(bigint) from public, anon;
revoke all on function public.kg_lar_grupper() from public, anon;
revoke all on function public.kg_lar_grupp_skapa(text) from public, anon;
revoke all on function public.kg_lar_grupp_andra(bigint,text) from public, anon;
revoke all on function public.kg_lar_grupp_ta_bort(bigint) from public, anon;
revoke all on function public.kg_lar_kollega(bigint,text) from public, anon;
revoke all on function public.kg_lar_ta_bort_elev(bigint,uuid) from public, anon;
revoke all on function public.kg_lar_elever(bigint) from public, anon;
revoke all on function public.kg_lar_elev(bigint,uuid) from public, anon;
revoke all on function public.kg_lar_grupp_omraden(bigint,text) from public, anon;
revoke all on function public.kg_admin_grupp_fran_klass(bigint,text) from public, anon;
revoke all on function public.kg_prov_skapa(text,text,text,text[],text[],integer,date,bigint[],text) from public, anon;
revoke all on function public.kg_prov_ta_bort(bigint) from public, anon;
grant execute on function public.kg_anslut_kod(text) to authenticated;
grant execute on function public.kg_mina_grupper() to authenticated;
grant execute on function public.kg_grupp_lamna(bigint) to authenticated;
grant execute on function public.kg_prov_dolj(bigint) to authenticated;
grant execute on function public.kg_lar_grupper() to authenticated;
grant execute on function public.kg_lar_grupp_skapa(text) to authenticated;
grant execute on function public.kg_lar_grupp_andra(bigint,text) to authenticated;
grant execute on function public.kg_lar_grupp_ta_bort(bigint) to authenticated;
grant execute on function public.kg_lar_kollega(bigint,text) to authenticated;
grant execute on function public.kg_lar_ta_bort_elev(bigint,uuid) to authenticated;
grant execute on function public.kg_lar_elever(bigint) to authenticated;
grant execute on function public.kg_lar_elev(bigint,uuid) to authenticated;
grant execute on function public.kg_lar_grupp_omraden(bigint,text) to authenticated;
grant execute on function public.kg_admin_grupp_fran_klass(bigint,text) to authenticated;
grant execute on function public.kg_prov_skapa(text,text,text,text[],text[],integer,date,bigint[],text) to authenticated;
grant execute on function public.kg_prov_ta_bort(bigint) to authenticated;
grant execute on function public.kg_prov_mina() to authenticated;
grant execute on function public.kg_prov_sammanstallning(bigint) to authenticated;
grant execute on function public.kg_prov_avsluta(bigint,boolean) to authenticated;
grant execute on function public.kg_prov_for_mig() to authenticated;
grant execute on function public.kg_prov_rapportera(bigint,integer,integer,jsonb) to authenticated;

commit;
