-- =====================================================================
-- Kunskapsgymmet: Plugga inför prov (lärarskapad provträning)
-- Kräver att sql/2026-10-01-klasser.sql och sql/2026-10-01-egna-klasser.sql
-- redan är körda. Kör hela filen i Supabase → SQL Editor. Den kan köras om
-- utan skada.
--
--   * public.kg_provtraning        provträningar som lärare skapar
--   * kg_private.provdeltagare     elever som gått med via kod eller länk
--   * kg_private.provresultat      elevens framsteg per provträning
--
-- Lärare:  kg_prov_skapa(...), kg_prov_mina(), kg_prov_sammanstallning(p_prov),
--          kg_prov_avsluta(p_prov)
-- Elev:    kg_prov_for_mig(), kg_prov_anslut(p_kod),
--          kg_prov_rapportera(p_prov,p_klara,p_ratt,p_omr)
--
-- Läraren väljer bara kurs, spår, områden (omr), nivåer och omfattning.
-- Uppgifterna väljs av Kunskapsgymmets vanliga träningsmotor i webbläsaren,
-- så två elever kan få olika uppgifter i samma provträning.
-- =====================================================================

begin;

create table if not exists public.kg_provtraning (
  id        bigint generated by default as identity primary key,
  kod       text not null,
  titel     text not null check (char_length(btrim(titel)) between 2 and 60),
  kurs      text not null check (kurs ~ '^[a-z0-9]{2,8}$'),
  spar      text check (spar is null or spar ~ '^[0-9a-z]{1,4}$'),
  omraden   text[] not null check (cardinality(omraden) between 1 and 60),
  nivaer    text[] not null check (cardinality(nivaer) between 1 and 3 and nivaer <@ array['E','C','A']),
  antal     integer not null check (antal between 5 and 100),
  datum     date,
  klass_id  bigint references public.kg_klass(id) on delete set null,
  larare    uuid not null,
  aktiv     boolean not null default true,
  skapad    timestamptz not null default now()
);
create unique index if not exists kg_provtraning_kod_uk on public.kg_provtraning (upper(kod));
create index if not exists kg_provtraning_klass_idx on public.kg_provtraning (klass_id);
create index if not exists kg_provtraning_larare_idx on public.kg_provtraning (larare);
alter table public.kg_provtraning enable row level security;   -- inga policys: all åtkomst via funktionerna

create table if not exists kg_private.provdeltagare (
  prov_id  bigint not null references public.kg_provtraning(id) on delete cascade,
  user_id  uuid not null,
  gick_med timestamptz not null default now(),
  primary key (prov_id, user_id)
);

create table if not exists kg_private.provresultat (
  prov_id     bigint not null references public.kg_provtraning(id) on delete cascade,
  user_id     uuid not null,
  klara       integer not null default 0,
  ratt        integer not null default 0,
  per_omr     jsonb not null default '{}'::jsonb,
  uppdaterad  timestamptz not null default now(),
  primary key (prov_id, user_id)
);

-- ---------------------------------------------------------------------
-- Hjälp: får inloggat konto skapa och se provträningar? Samma lärarbegrepp
-- som klassen Lärare (ul_ar_larare, kg_ar_larare eller admin).
CREATE OR REPLACE FUNCTION kg_private.prov_larare()
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO ''
AS $function$
  select coalesce(public.ul_ar_larare(),false) or coalesce(public.kg_ar_larare(),false) or coalesce(public.kg_ar_admin(),false)
$function$;

CREATE OR REPLACE FUNCTION kg_private.prov_json(p public.kg_provtraning, p_uid uuid)
 RETURNS jsonb
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO ''
AS $function$
  select jsonb_build_object(
    'id',p.id,'kod',p.kod,'titel',p.titel,'kurs',p.kurs,'spar',p.spar,
    'omraden',to_jsonb(p.omraden),'nivaer',to_jsonb(p.nivaer),'antal',p.antal,
    'datum',p.datum,'aktiv',p.aktiv,
    'klass',(select k.namn from public.kg_klass k where k.id = p.klass_id),
    'klara',coalesce((select r.klara from kg_private.provresultat r where r.prov_id=p.id and r.user_id=p_uid),0),
    'ratt',coalesce((select r.ratt from kg_private.provresultat r where r.prov_id=p.id and r.user_id=p_uid),0))
$function$;

-- ---------------------------------------------------------------------
-- Lärare: skapa provträning. p_kod är ett förslag; servern gör den unik.
CREATE OR REPLACE FUNCTION public.kg_prov_skapa(
  p_titel text, p_kurs text, p_spar text, p_omraden text[], p_nivaer text[],
  p_antal integer, p_datum date, p_klass bigint, p_kod text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare uid uuid := auth.uid(); v_kod text; v_bas text; n int := 1; v_id bigint; v_titel text;
begin
  if uid is null then return jsonb_build_object('ok',false,'code','ej_inloggad'); end if;
  if not kg_private.prov_larare() then return jsonb_build_object('ok',false,'code','larare_kravs'); end if;
  v_titel := regexp_replace(btrim(coalesce(p_titel,'')), '\s+', ' ', 'g');
  if char_length(v_titel) not between 2 and 60 then return jsonb_build_object('ok',false,'code','titel'); end if;
  if coalesce(cardinality(p_omraden),0) = 0 then return jsonb_build_object('ok',false,'code','omraden'); end if;
  if coalesce(cardinality(p_nivaer),0) = 0 or not (p_nivaer <@ array['E','C','A']) then
    return jsonb_build_object('ok',false,'code','nivaer');
  end if;
  if p_antal is null or p_antal not between 5 and 100 then return jsonb_build_object('ok',false,'code','antal'); end if;
  if p_klass is not null and not exists (select 1 from public.kg_klass where id = p_klass) then
    return jsonb_build_object('ok',false,'code','okand_klass');
  end if;
  v_bas := upper(regexp_replace(coalesce(nullif(btrim(p_kod),''),v_titel), '[^A-Za-z0-9ÅÄÖåäö-]+', '-', 'g'));
  v_bas := translate(v_bas, 'ÅÄÖ', 'AAO');
  v_bas := btrim(left(regexp_replace(v_bas, '-{2,}', '-', 'g'), 24), '-');
  if char_length(v_bas) < 3 then v_bas := 'PROV-' || to_char(now(),'YYMMDD'); end if;
  v_kod := v_bas;
  while exists (select 1 from public.kg_provtraning where upper(kod) = upper(v_kod)) loop
    n := n + 1; v_kod := v_bas || '-' || n;
  end loop;
  insert into public.kg_provtraning(kod,titel,kurs,spar,omraden,nivaer,antal,datum,klass_id,larare)
  values (v_kod, v_titel, lower(p_kurs), nullif(lower(btrim(coalesce(p_spar,''))),''), p_omraden, p_nivaer,
          p_antal, p_datum, p_klass, uid)
  returning id into v_id;
  return jsonb_build_object('ok',true,'id',v_id,'kod',v_kod);
end $function$;

-- Lärare: egna provträningar med en kort sammanfattning.
CREATE OR REPLACE FUNCTION public.kg_prov_mina()
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare uid uuid := auth.uid();
begin
  if uid is null or not kg_private.prov_larare() then return jsonb_build_object('ok',false,'code','larare_kravs'); end if;
  return jsonb_build_object('ok',true,'prov',coalesce((
    select jsonb_agg(kg_private.prov_json(p, uid) || jsonb_build_object(
             'tranat',(select count(*) from kg_private.provresultat r where r.prov_id=p.id and r.klara>0))
           order by p.aktiv desc, p.datum nulls last, p.skapad desc)
      from public.kg_provtraning p
     where p.larare = uid or public.kg_ar_admin()), '[]'::jsonb));
end $function$;

-- Lärare: sammanställning per område för en provträning.
CREATE OR REPLACE FUNCTION public.kg_prov_sammanstallning(p_prov bigint)
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare uid uuid := auth.uid(); p public.kg_provtraning%rowtype; v_elever int; v_tranat int; v_omr jsonb; v_klara int;
begin
  if uid is null then return jsonb_build_object('ok',false,'code','ej_inloggad'); end if;
  select * into p from public.kg_provtraning where id = p_prov;
  if not found then return jsonb_build_object('ok',false,'code','okand'); end if;
  if p.larare <> uid and not public.kg_ar_admin() then return jsonb_build_object('ok',false,'code','larare_kravs'); end if;
  -- Eleverna = klassens medlemmar (utom lärarklassen) plus de som gått med via kod.
  with elever as (
    select m.user_id from kg_private.klassmedlem m
      join public.kg_klass k on k.id = m.klass_id
     where p.klass_id is not null and m.klass_id = p.klass_id and not k.larare
    union
    select d.user_id from kg_private.provdeltagare d where d.prov_id = p.id
    union
    select r.user_id from kg_private.provresultat r where r.prov_id = p.id
  )
  select count(*) into v_elever from elever;
  select count(*), coalesce(sum(klara),0) into v_tranat, v_klara
    from kg_private.provresultat where prov_id = p.id and klara > 0;
  select coalesce(jsonb_object_agg(o, jsonb_build_object('forsok',f,'ratt',r,'elever',e)), '{}'::jsonb) into v_omr
    from (
      select o.key as o,
             sum(coalesce((o.value->>'f')::int,0)) as f,
             sum(coalesce((o.value->>'r')::int,0)) as r,
             count(*) filter (where coalesce((o.value->>'f')::int,0) > 0) as e
        from kg_private.provresultat res, jsonb_each(res.per_omr) o
       where res.prov_id = p.id
       group by o.key
    ) x;
  return jsonb_build_object('ok',true,'elever',v_elever,'tranat',v_tranat,'uppgifter',v_klara,
                            'omraden',v_omr,'prov',kg_private.prov_json(p, uid));
end $function$;

-- Lärare: avsluta (dölj för elever) eller återaktivera.
CREATE OR REPLACE FUNCTION public.kg_prov_avsluta(p_prov bigint, p_aktiv boolean DEFAULT false)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare uid uuid := auth.uid();
begin
  update public.kg_provtraning set aktiv = coalesce(p_aktiv,false)
   where id = p_prov and (larare = uid or public.kg_ar_admin());
  if not found then return jsonb_build_object('ok',false,'code','okand'); end if;
  return jsonb_build_object('ok',true);
end $function$;

-- ---------------------------------------------------------------------
-- Elev: aktiva provträningar för min klass och de jag gått med i.
-- En provträning visas till och med dagen efter provdatumet.
CREATE OR REPLACE FUNCTION public.kg_prov_for_mig()
 RETURNS jsonb
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO ''
AS $function$
  select coalesce(jsonb_agg(kg_private.prov_json(p, auth.uid()) order by p.datum nulls last, p.id), '[]'::jsonb)
    from public.kg_provtraning p
   where auth.uid() is not null and p.aktiv
     and (p.datum is null or p.datum >= ((now() at time zone 'Europe/Stockholm')::date - 1))
     and (
       exists (select 1 from kg_private.klassmedlem m where m.user_id = auth.uid() and m.klass_id = p.klass_id)
       or exists (select 1 from kg_private.provdeltagare d where d.user_id = auth.uid() and d.prov_id = p.id)
     )
$function$;

-- Elev: gå med via kod (eller länk med ?prov=KOD).
CREATE OR REPLACE FUNCTION public.kg_prov_anslut(p_kod text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare uid uuid := auth.uid(); p public.kg_provtraning%rowtype;
begin
  if uid is null then return jsonb_build_object('ok',false,'code','ej_inloggad'); end if;
  select * into p from public.kg_provtraning where upper(kod) = upper(btrim(coalesce(p_kod,''))) and aktiv;
  if not found then return jsonb_build_object('ok',false,'code','okand'); end if;
  insert into kg_private.provdeltagare(prov_id,user_id) values (p.id, uid) on conflict do nothing;
  return jsonb_build_object('ok',true,'prov',kg_private.prov_json(p, uid));
end $function$;

-- Elev: rapportera framsteg. p_omr = {"omr":{"f":försök,"r":rätt}, ...}.
-- Klientens ögonblicksbild ersätter den gamla, men antalet kan inte minska.
CREATE OR REPLACE FUNCTION public.kg_prov_rapportera(p_prov bigint, p_klara integer, p_ratt integer, p_omr jsonb)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare uid uuid := auth.uid(); p public.kg_provtraning%rowtype; v_omr jsonb := '{}'::jsonb; o record;
begin
  if uid is null then return jsonb_build_object('ok',false,'code','ej_inloggad'); end if;
  select * into p from public.kg_provtraning where id = p_prov;
  if not found then return jsonb_build_object('ok',false,'code','okand'); end if;
  if not (exists (select 1 from kg_private.klassmedlem m where m.user_id = uid and m.klass_id = p.klass_id)
          or exists (select 1 from kg_private.provdeltagare d where d.user_id = uid and d.prov_id = p.id)) then
    return jsonb_build_object('ok',false,'code','ej_deltagare');
  end if;
  -- Bara provets egna områden och rimliga tal sparas.
  if jsonb_typeof(p_omr) = 'object' then
    for o in select key, value from jsonb_each(p_omr) loop
      if o.key = any(p.omraden) and jsonb_typeof(o.value) = 'object' then
        v_omr := v_omr || jsonb_build_object(o.key, jsonb_build_object(
          'f', least(greatest(coalesce((o.value->>'f')::int,0),0),1000),
          'r', least(greatest(coalesce((o.value->>'r')::int,0),0),1000)));
      end if;
    end loop;
  end if;
  insert into kg_private.provresultat(prov_id,user_id,klara,ratt,per_omr,uppdaterad)
  values (p.id, uid, least(greatest(coalesce(p_klara,0),0),1000), least(greatest(coalesce(p_ratt,0),0),1000), v_omr, now())
  on conflict (prov_id,user_id) do update
    set klara = greatest(kg_private.provresultat.klara, excluded.klara),
        ratt = greatest(kg_private.provresultat.ratt, excluded.ratt),
        per_omr = excluded.per_omr,
        uppdaterad = now();
  return jsonb_build_object('ok',true);
end $function$;

revoke all on function public.kg_prov_skapa(text,text,text,text[],text[],integer,date,bigint,text) from public, anon;
revoke all on function public.kg_prov_mina() from public, anon;
revoke all on function public.kg_prov_sammanstallning(bigint) from public, anon;
revoke all on function public.kg_prov_avsluta(bigint,boolean) from public, anon;
revoke all on function public.kg_prov_for_mig() from public, anon;
revoke all on function public.kg_prov_anslut(text) from public, anon;
revoke all on function public.kg_prov_rapportera(bigint,integer,integer,jsonb) from public, anon;
grant execute on function public.kg_prov_skapa(text,text,text,text[],text[],integer,date,bigint,text) to authenticated;
grant execute on function public.kg_prov_mina() to authenticated;
grant execute on function public.kg_prov_sammanstallning(bigint) to authenticated;
grant execute on function public.kg_prov_avsluta(bigint,boolean) to authenticated;
grant execute on function public.kg_prov_for_mig() to authenticated;
grant execute on function public.kg_prov_anslut(text) to authenticated;
grant execute on function public.kg_prov_rapportera(bigint,integer,integer,jsonb) to authenticated;

commit;
