-- =====================================================================
-- Kunskapsgymmet: skolor, lärarprofiler, synliga grupper, redigera pass
-- Kräver att 2026-10-02-provtraning.sql och 2026-10-03-larargrupper.sql
-- redan är körda. Kör hela filen i Supabase → SQL Editor. Den kan köras om
-- utan skada.
--
--   * public.kg_skola            skolor (lärarna anger sin skola själva)
--   * kg_private.larprofil       lärarens fullständiga namn och skola
--   * kg_grupp.synlig            gruppen syns i skolans lista, så elever kan
--                                gå med utan kod
--   * kg_provtraning.alla        passet omfattar alla uppgifter i områdena
--
-- Den som fyller i en lärarprofil blir lärare i Kunskapsgymmet direkt och kan
-- skapa grupper och träningspass. Felrapporter, Uppgiftslabbet och klassen
-- Lärare på topplistan kräver fortfarande ett godkänt lärarkonto. Admin kan
-- stänga av en lärarprofil.
--
-- Lärare: kg_min_larprofil(), kg_bli_larare(p_namn,p_skola),
--         kg_lar_grupp_synlig(p_grupp,p_synlig), kg_prov_andra(...)
-- Elev:   kg_skolor(p_sok), kg_skola_larare(p_skola), kg_grupp_ga_med(p_grupp)
-- Admin:  kg_admin_larare(), kg_admin_larare_aktiv(p_user,p_aktiv)
-- =====================================================================

begin;

create table if not exists public.kg_skola (
  id         bigint generated by default as identity primary key,
  namn       text not null check (char_length(btrim(namn)) between 2 and 80),
  skapad     timestamptz not null default now(),
  skapad_av  uuid
);
create unique index if not exists kg_skola_namn_uk on public.kg_skola (lower(btrim(namn)));
alter table public.kg_skola enable row level security;   -- inga policys: all åtkomst via funktionerna

create table if not exists kg_private.larprofil (
  user_id   uuid primary key,
  namn      text not null check (char_length(btrim(namn)) between 3 and 80),
  skola_id  bigint references public.kg_skola(id) on delete set null,
  aktiv     boolean not null default true,
  skapad    timestamptz not null default now(),
  andrad    timestamptz not null default now()
);
create index if not exists larprofil_skola_idx on kg_private.larprofil (skola_id);

alter table public.kg_grupp add column if not exists synlig boolean not null default true;
alter table public.kg_provtraning add column if not exists alla boolean not null default false;
alter table public.kg_provtraning drop constraint if exists kg_provtraning_antal_check;
alter table public.kg_provtraning add constraint kg_provtraning_antal_check check (antal between 1 and 5000);

-- ---------------------------------------------------------------------
-- Vem räknas som lärare för grupper och träningspass: godkända lärare,
-- admin och konton med en aktiv lärarprofil.
CREATE OR REPLACE FUNCTION kg_private.prov_larare()
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO ''
AS $function$
  select coalesce(public.ul_ar_larare(),false) or coalesce(public.kg_ar_larare(),false) or coalesce(public.kg_ar_admin(),false)
      or exists (select 1 from kg_private.larprofil l where l.user_id = auth.uid() and l.aktiv)
$function$;

-- Lärarens namn: lärarprofilen i första hand, annars kontots namn.
CREATE OR REPLACE FUNCTION kg_private.anv_namn(p_uid uuid)
 RETURNS text
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO ''
AS $function$
  select coalesce((select l.namn from kg_private.larprofil l where l.user_id = p_uid),
                  nullif(btrim(u.raw_user_meta_data->>'full_name'),''),
                  nullif(btrim(u.raw_user_meta_data->>'name'),''),
                  split_part(u.email,'@',1))
    from auth.users u where u.id = p_uid
$function$;

CREATE OR REPLACE FUNCTION kg_private.prov_json(p public.kg_provtraning, p_uid uuid)
 RETURNS jsonb
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO ''
AS $function$
  select jsonb_build_object(
    'id',p.id,'kod',p.kod,'titel',p.titel,'kurs',p.kurs,'spar',p.spar,
    'omraden',to_jsonb(p.omraden),'nivaer',to_jsonb(p.nivaer),'antal',p.antal,'alla',p.alla,
    'datum',p.datum,'aktiv',p.aktiv,
    'klass',(select k.namn from public.kg_klass k where k.id = p.klass_id),
    'larare',kg_private.anv_namn(p.larare),
    'klara',coalesce((select r.klara from kg_private.provresultat r where r.prov_id=p.id and r.user_id=p_uid),0),
    'ratt',coalesce((select r.ratt from kg_private.provresultat r where r.prov_id=p.id and r.user_id=p_uid),0))
$function$;

-- ---------------------------------------------------------------------
-- Lärarprofil
CREATE OR REPLACE FUNCTION public.kg_min_larprofil()
 RETURNS jsonb
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO ''
AS $function$
  select jsonb_build_object(
    'larare', auth.uid() is not null and kg_private.prov_larare(),
    'godkand', auth.uid() is not null and kg_private.ar_larare(auth.uid()),
    'profil', (select jsonb_build_object('namn',l.namn,'aktiv',l.aktiv,
                 'skola',(select jsonb_build_object('id',s.id,'namn',s.namn) from public.kg_skola s where s.id = l.skola_id))
                 from kg_private.larprofil l where l.user_id = auth.uid()))
$function$;

CREATE OR REPLACE FUNCTION public.kg_bli_larare(p_namn text, p_skola text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare uid uuid := auth.uid(); v_namn text; v_skola text; v_sid bigint; v_aktiv boolean;
begin
  if uid is null then return jsonb_build_object('ok',false,'code','ej_inloggad'); end if;
  v_namn := regexp_replace(btrim(coalesce(p_namn,'')), '\s+', ' ', 'g');
  v_skola := regexp_replace(btrim(coalesce(p_skola,'')), '\s+', ' ', 'g');
  if char_length(v_namn) not between 3 and 80 or v_namn !~ ' ' then
    return jsonb_build_object('ok',false,'code','namn');
  end if;
  if char_length(v_skola) not between 2 and 80 then return jsonb_build_object('ok',false,'code','skola'); end if;
  select aktiv into v_aktiv from kg_private.larprofil where user_id = uid;
  if v_aktiv = false then return jsonb_build_object('ok',false,'code','avstangd'); end if;
  select id into v_sid from public.kg_skola where lower(btrim(namn)) = lower(v_skola);
  if v_sid is null then
    insert into public.kg_skola(namn,skapad_av) values (v_skola, uid)
    on conflict ((lower(btrim(namn)))) do nothing
    returning id into v_sid;
    if v_sid is null then select id into v_sid from public.kg_skola where lower(btrim(namn)) = lower(v_skola); end if;
  end if;
  insert into kg_private.larprofil(user_id,namn,skola_id) values (uid, v_namn, v_sid)
  on conflict (user_id) do update set namn = excluded.namn, skola_id = excluded.skola_id, andrad = now();
  return jsonb_build_object('ok',true) || public.kg_min_larprofil();
end $function$;

-- ---------------------------------------------------------------------
-- Skolor och lärare för eleven
CREATE OR REPLACE FUNCTION public.kg_skolor(p_sok text DEFAULT '')
 RETURNS jsonb
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO ''
AS $function$
  select coalesce(jsonb_agg(jsonb_build_object('id',x.id,'namn',x.namn,'larare',x.n) order by x.n desc, x.namn), '[]'::jsonb)
    from (
      select s.id, s.namn, count(l.user_id) n
        from public.kg_skola s
        join kg_private.larprofil l on l.skola_id = s.id and l.aktiv
       where auth.uid() is not null
         and (coalesce(btrim(p_sok),'') = '' or s.namn ilike '%' || btrim(p_sok) || '%')
       group by s.id, s.namn
       order by count(l.user_id) desc, s.namn
       limit 30
    ) x
$function$;

CREATE OR REPLACE FUNCTION public.kg_skola_larare(p_skola bigint)
 RETURNS jsonb
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO ''
AS $function$
  select coalesce(jsonb_agg(jsonb_build_object(
           'id',l.user_id,'namn',l.namn,'godkand',kg_private.ar_larare(l.user_id),
           'grupper',(select coalesce(jsonb_agg(jsonb_build_object('id',g.id,'namn',g.namn,
                         'med',exists (select 1 from kg_private.gruppmedlem m where m.grupp_id = g.id and m.user_id = auth.uid()))
                       order by g.namn), '[]'::jsonb)
                        from public.kg_grupp g
                       where g.synlig
                         and exists (select 1 from kg_private.grupplarare gl where gl.grupp_id = g.id and gl.user_id = l.user_id)))
         order by l.namn), '[]'::jsonb)
    from kg_private.larprofil l
   where auth.uid() is not null and l.skola_id = p_skola and l.aktiv
$function$;

CREATE OR REPLACE FUNCTION public.kg_grupp_ga_med(p_grupp bigint)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare g public.kg_grupp%rowtype;
begin
  if auth.uid() is null then return jsonb_build_object('ok',false,'code','ej_inloggad'); end if;
  select * into g from public.kg_grupp where id = p_grupp and synlig;
  if not found then return jsonb_build_object('ok',false,'code','okand'); end if;
  insert into kg_private.gruppmedlem(grupp_id,user_id) values (g.id, auth.uid()) on conflict do nothing;
  return jsonb_build_object('ok',true,'typ','grupp','grupp',jsonb_build_object('id',g.id,'namn',g.namn,
    'larare',(select coalesce(jsonb_agg(kg_private.anv_namn(l.user_id) order by l.satt),'[]'::jsonb)
                from kg_private.grupplarare l where l.grupp_id = g.id)));
end $function$;

-- ---------------------------------------------------------------------
-- Lärare: grupper (nu med synlighet)
CREATE OR REPLACE FUNCTION public.kg_lar_grupper()
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare uid uuid := auth.uid();
begin
  if uid is null or not kg_private.prov_larare() then return jsonb_build_object('ok',false,'code','larare_kravs'); end if;
  return jsonb_build_object('ok',true,'grupper',coalesce((
    select jsonb_agg(jsonb_build_object(
             'id',g.id,'namn',g.namn,'kod',g.kod,'skapad',g.skapad,'egen',g.skapad_av = uid,'synlig',g.synlig,
             'elever',(select count(*) from kg_private.gruppmedlem m where m.grupp_id = g.id),
             'aktiva',(select count(distinct m.user_id) from kg_private.gruppmedlem m
                        where m.grupp_id = g.id
                          and exists (select 1 from kg_private.elev_forsok(m.user_id) f
                                       where f.tid > now() - interval '7 days')),
             'larare',(select coalesce(jsonb_agg(kg_private.anv_namn(l.user_id) order by l.satt),'[]'::jsonb)
                         from kg_private.grupplarare l where l.grupp_id = g.id))
           order by g.namn)
      from public.kg_grupp g
     where exists (select 1 from kg_private.grupplarare l where l.grupp_id = g.id and l.user_id = uid)),
    '[]'::jsonb));
end $function$;

CREATE OR REPLACE FUNCTION public.kg_lar_grupp_synlig(p_grupp bigint, p_synlig boolean)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
begin
  if not kg_private.lar_har_grupp(p_grupp) then return jsonb_build_object('ok',false,'code','larare_kravs'); end if;
  update public.kg_grupp set synlig = coalesce(p_synlig,true) where id = p_grupp;
  return jsonb_build_object('ok',true);
end $function$;

-- ---------------------------------------------------------------------
-- Träningspass: skapa (nu med "alla uppgifter") och redigera
drop function if exists public.kg_prov_skapa(text,text,text,text[],text[],integer,date,bigint[],text);
CREATE OR REPLACE FUNCTION public.kg_prov_skapa(
  p_titel text, p_kurs text, p_spar text, p_omraden text[], p_nivaer text[],
  p_antal integer, p_alla boolean, p_datum date, p_grupper bigint[], p_kod text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare uid uuid := auth.uid(); v_kod text; v_bas text; n int := 1; v_id bigint; v_titel text; g bigint;
begin
  if uid is null then return jsonb_build_object('ok',false,'code','ej_inloggad'); end if;
  if not kg_private.prov_larare() then return jsonb_build_object('ok',false,'code','larare_kravs'); end if;
  v_titel := regexp_replace(btrim(coalesce(p_titel,'')), '\s+', ' ', 'g');
  if char_length(v_titel) not between 2 and 60 then return jsonb_build_object('ok',false,'code','titel'); end if;
  if coalesce(cardinality(p_omraden),0) = 0 then return jsonb_build_object('ok',false,'code','omraden'); end if;
  if coalesce(cardinality(p_nivaer),0) = 0 or not (p_nivaer <@ array['E','C','A']) then
    return jsonb_build_object('ok',false,'code','nivaer');
  end if;
  if p_antal is null or p_antal not between 1 and 5000 then return jsonb_build_object('ok',false,'code','antal'); end if;
  foreach g in array coalesce(p_grupper,'{}') loop
    if not kg_private.lar_har_grupp(g) then return jsonb_build_object('ok',false,'code','okand_grupp'); end if;
  end loop;
  v_bas := upper(regexp_replace(coalesce(nullif(btrim(p_kod),''),v_titel), '[^A-Za-z0-9ÅÄÖåäö-]+', '-', 'g'));
  v_bas := translate(v_bas, 'ÅÄÖ', 'AAO');
  v_bas := btrim(left(regexp_replace(v_bas, '-{2,}', '-', 'g'), 24), '-');
  if char_length(v_bas) < 3 then v_bas := 'PASS-' || to_char(now(),'YYMMDD'); end if;
  v_kod := v_bas;
  while exists (select 1 from public.kg_provtraning where upper(kod) = upper(v_kod))
     or exists (select 1 from public.kg_grupp where upper(kod) = upper(v_kod)) loop
    n := n + 1; v_kod := v_bas || '-' || n;
  end loop;
  insert into public.kg_provtraning(kod,titel,kurs,spar,omraden,nivaer,antal,alla,datum,klass_id,larare,grupper)
  values (v_kod, v_titel, lower(p_kurs), nullif(lower(btrim(coalesce(p_spar,''))),''), p_omraden, p_nivaer,
          p_antal, coalesce(p_alla,false), p_datum, null, uid, coalesce(p_grupper,'{}'))
  returning id into v_id;
  return jsonb_build_object('ok',true,'id',v_id,'kod',v_kod);
end $function$;

-- Kursen kan inte bytas i efterhand, eftersom elevernas resultat hör till kursens områden.
CREATE OR REPLACE FUNCTION public.kg_prov_andra(
  p_prov bigint, p_titel text, p_spar text, p_omraden text[], p_nivaer text[],
  p_antal integer, p_alla boolean, p_datum date, p_grupper bigint[])
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare p public.kg_provtraning%rowtype; v_titel text; g bigint;
begin
  select * into p from public.kg_provtraning where id = p_prov;
  if not found or not kg_private.prov_lar_kan(p) then return jsonb_build_object('ok',false,'code','okand'); end if;
  v_titel := regexp_replace(btrim(coalesce(p_titel,'')), '\s+', ' ', 'g');
  if char_length(v_titel) not between 2 and 60 then return jsonb_build_object('ok',false,'code','titel'); end if;
  if coalesce(cardinality(p_omraden),0) = 0 then return jsonb_build_object('ok',false,'code','omraden'); end if;
  if coalesce(cardinality(p_nivaer),0) = 0 or not (p_nivaer <@ array['E','C','A']) then
    return jsonb_build_object('ok',false,'code','nivaer');
  end if;
  if p_antal is null or p_antal not between 1 and 5000 then return jsonb_build_object('ok',false,'code','antal'); end if;
  -- Läraren får bara lägga till sina egna grupper, men behåller grupper som en kollega redan lagt till.
  foreach g in array coalesce(p_grupper,'{}') loop
    if not (g = any(p.grupper)) and not kg_private.lar_har_grupp(g) then
      return jsonb_build_object('ok',false,'code','okand_grupp');
    end if;
  end loop;
  update public.kg_provtraning
     set titel = v_titel, spar = nullif(lower(btrim(coalesce(p_spar,''))),''), omraden = p_omraden,
         nivaer = p_nivaer, antal = p_antal, alla = coalesce(p_alla,false), datum = p_datum,
         grupper = coalesce(p_grupper,'{}')
   where id = p_prov;
  return jsonb_build_object('ok',true,'id',p_prov,'kod',p.kod);
end $function$;

-- ---------------------------------------------------------------------
-- Admin: lärarprofiler
CREATE OR REPLACE FUNCTION public.kg_admin_larare()
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO ''
AS $function$
begin
  if not coalesce(public.kg_ar_admin(),false) then return jsonb_build_object('ok',false,'code','admin_kravs'); end if;
  return jsonb_build_object('ok',true,'larare',coalesce((
    select jsonb_agg(jsonb_build_object(
             'id',l.user_id,'namn',l.namn,'aktiv',l.aktiv,'skapad',l.skapad,
             'epost',(select u.email from auth.users u where u.id = l.user_id),
             'skola',(select s.namn from public.kg_skola s where s.id = l.skola_id),
             'godkand',kg_private.ar_larare(l.user_id),
             'grupper',(select count(*) from kg_private.grupplarare gl where gl.user_id = l.user_id),
             'elever',(select count(distinct m.user_id) from kg_private.gruppmedlem m
                        join kg_private.grupplarare gl on gl.grupp_id = m.grupp_id where gl.user_id = l.user_id))
           order by l.skapad desc)
      from kg_private.larprofil l), '[]'::jsonb));
end $function$;

CREATE OR REPLACE FUNCTION public.kg_admin_larare_aktiv(p_user uuid, p_aktiv boolean)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
begin
  if not coalesce(public.kg_ar_admin(),false) then return jsonb_build_object('ok',false,'code','admin_kravs'); end if;
  update kg_private.larprofil set aktiv = coalesce(p_aktiv,true), andrad = now() where user_id = p_user;
  return jsonb_build_object('ok',true);
end $function$;

-- ---------------------------------------------------------------------
revoke all on function public.kg_min_larprofil() from public, anon;
revoke all on function public.kg_bli_larare(text,text) from public, anon;
revoke all on function public.kg_skolor(text) from public, anon;
revoke all on function public.kg_skola_larare(bigint) from public, anon;
revoke all on function public.kg_grupp_ga_med(bigint) from public, anon;
revoke all on function public.kg_lar_grupp_synlig(bigint,boolean) from public, anon;
revoke all on function public.kg_prov_skapa(text,text,text,text[],text[],integer,boolean,date,bigint[],text) from public, anon;
revoke all on function public.kg_prov_andra(bigint,text,text,text[],text[],integer,boolean,date,bigint[]) from public, anon;
revoke all on function public.kg_admin_larare() from public, anon;
revoke all on function public.kg_admin_larare_aktiv(uuid,boolean) from public, anon;
grant execute on function public.kg_min_larprofil() to authenticated;
grant execute on function public.kg_bli_larare(text,text) to authenticated;
grant execute on function public.kg_skolor(text) to authenticated;
grant execute on function public.kg_skola_larare(bigint) to authenticated;
grant execute on function public.kg_grupp_ga_med(bigint) to authenticated;
grant execute on function public.kg_lar_grupp_synlig(bigint,boolean) to authenticated;
grant execute on function public.kg_prov_skapa(text,text,text,text[],text[],integer,boolean,date,bigint[],text) to authenticated;
grant execute on function public.kg_prov_andra(bigint,text,text,text[],text[],integer,boolean,date,bigint[]) to authenticated;
grant execute on function public.kg_admin_larare() to authenticated;
grant execute on function public.kg_admin_larare_aktiv(uuid,boolean) to authenticated;
grant execute on function public.kg_lar_grupper() to authenticated;

commit;
