-- =====================================================================
-- Kunskapsgymmet: klasser och klasstopplista
-- Kör hela filen i Supabase → SQL Editor. Den kan köras om utan skada.
--
--   * public.kg_klass            klasserna (läses bara via funktionerna)
--   * kg_private.klassmedlem     vilken klass varje konto tillhör
--   * Klassen "Lärare" skapas automatiskt och kräver lärar- eller adminkonto.
--
-- Elev:   kg_klasser(), kg_min_klass(), kg_valj_klass(p_klass)
--         Byte av klass högst en gång per 7 dagar (admin kan alltid flytta).
-- Admin:  kg_admin_klasser(), kg_admin_klass_spara(p_id,p_namn,p_ordning),
--         kg_admin_klass_ta_bort(p_id), kg_admin_satt_klass(p_user,p_klass)
-- Lista:  topplista_klasser(p_period), topplista_klass_elever(p_klass,p_period)
--
-- Klassens poäng = snitt-XP per elev under perioden, där varje elev räknas
-- med högst taket för perioden (dag 400, vecka 2000, månad 6000, totalt
-- 30000). Alla i klassen räknas i snittet, så varje elev som tränar lyfter
-- laget. Konton som är flaggade för fusk räknas inte.
-- XP beräknas som i topplista_period: XP + 100 per medalj.
-- =====================================================================

begin;

create table if not exists public.kg_klass (
  id      bigint generated by default as identity primary key,
  namn    text not null check (char_length(btrim(namn)) between 1 and 40),
  ordning integer not null default 0,
  larare  boolean not null default false,
  skapad  timestamptz not null default now()
);
create unique index if not exists kg_klass_namn_uk on public.kg_klass (lower(btrim(namn)));
alter table public.kg_klass enable row level security;   -- inga policys: all åtkomst via funktionerna

create table if not exists kg_private.klassmedlem (
  user_id  uuid primary key,
  klass_id bigint not null references public.kg_klass(id) on delete cascade,
  satt     timestamptz not null default now(),
  satt_av  uuid
);
create index if not exists klassmedlem_klass_idx on kg_private.klassmedlem (klass_id);

insert into public.kg_klass (namn, ordning, larare)
select 'Lärare', -1, true
 where not exists (select 1 from public.kg_klass where larare);

-- ---------------------------------------------------------------------
-- Hjälpfunktion: XP och uppgifter för ett konto sedan p_start
-- (p_start null = totalt). Samma beräkning som topplista_period.
CREATE OR REPLACE FUNCTION kg_private.klass_period(p_uid uuid, p_start timestamptz)
 RETURNS TABLE(xp bigint, uppgifter bigint)
 LANGUAGE sql
 STABLE
 SET search_path TO ''
AS $function$
  with cur as (
    select coalesce((s.data->>'xp')::bigint,0) as x,
           coalesce((s.data->>'attempts')::bigint,0) as a,
           (select count(*)::bigint from jsonb_object_keys(coalesce(s.data->'badges','{}'::jsonb))) as m
      from kg_private.state s where s.id = p_uid
  ),
  base as (
    select coalesce((h.data->>'xp')::bigint,0) as x,
           coalesce((h.data->>'attempts')::bigint,0) as a,
           (select count(*)::bigint from jsonb_object_keys(coalesce(h.data->'badges','{}'::jsonb))) as m
      from kg_private.history h
     where p_start is not null and h.user_id = p_uid and h.saved_at >= p_start
     order by h.saved_at asc, h.id asc
     limit 1
  )
  select case when p_start is null then c.x + 100*c.m
              else greatest(0, (c.x - coalesce(b.x,c.x)) + 100*(c.m - coalesce(b.m,c.m))) end,
         case when p_start is null then c.a
              else greatest(0, c.a - coalesce(b.a,c.a)) end
    from cur c left join base b on true
$function$;

CREATE OR REPLACE FUNCTION kg_private.klass_start(p_period text)
 RETURNS timestamptz
 LANGUAGE sql
 STABLE
 SET search_path TO ''
AS $function$
  select case p_period
    when 'dag'   then date_trunc('day',   now() at time zone 'Europe/Stockholm') at time zone 'Europe/Stockholm'
    when 'vecka' then date_trunc('week',  now() at time zone 'Europe/Stockholm') at time zone 'Europe/Stockholm'
    when 'manad' then date_trunc('month', now() at time zone 'Europe/Stockholm') at time zone 'Europe/Stockholm'
    else null end
$function$;

CREATE OR REPLACE FUNCTION kg_private.klass_tak(p_period text)
 RETURNS bigint
 LANGUAGE sql
 IMMUTABLE
 SET search_path TO ''
AS $function$
  select case p_period when 'dag' then 400 when 'vecka' then 2000 when 'manad' then 6000 else 30000 end::bigint
$function$;

-- ---------------------------------------------------------------------
-- Elev
CREATE OR REPLACE FUNCTION public.kg_klasser()
 RETURNS jsonb
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO ''
AS $function$
  select coalesce(jsonb_agg(jsonb_build_object('id',k.id,'namn',k.namn,'larare',k.larare)
                            order by k.ordning, lower(k.namn)), '[]'::jsonb)
    from public.kg_klass k
$function$;

CREATE OR REPLACE FUNCTION public.kg_min_klass()
 RETURNS jsonb
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO ''
AS $function$
  select jsonb_build_object('id',k.id,'namn',k.namn,'larare',k.larare,'satt',m.satt)
    from kg_private.klassmedlem m join public.kg_klass k on k.id = m.klass_id
   where m.user_id = auth.uid()
$function$;

CREATE OR REPLACE FUNCTION public.kg_valj_klass(p_klass bigint)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare uid uuid := auth.uid(); k public.kg_klass%rowtype; m kg_private.klassmedlem%rowtype;
begin
  if uid is null then return jsonb_build_object('ok',false,'code','ej_inloggad'); end if;
  select * into m from kg_private.klassmedlem where user_id = uid;
  if found and m.klass_id is not distinct from p_klass then
    return jsonb_build_object('ok',true);
  end if;
  if found and m.satt > now() - interval '7 days' and not public.kg_ar_admin() then
    return jsonb_build_object('ok',false,'code','for_tidigt','tidigast',m.satt + interval '7 days');
  end if;
  if p_klass is null then
    delete from kg_private.klassmedlem where user_id = uid;
    return jsonb_build_object('ok',true);
  end if;
  select * into k from public.kg_klass where id = p_klass;
  if not found then return jsonb_build_object('ok',false,'code','okand_klass'); end if;
  if k.larare and not (public.kg_ar_larare() or public.kg_ar_admin()) then
    return jsonb_build_object('ok',false,'code','larare_kravs');
  end if;
  insert into kg_private.klassmedlem(user_id,klass_id,satt,satt_av) values(uid,p_klass,now(),uid)
    on conflict (user_id) do update set klass_id = excluded.klass_id, satt = now(), satt_av = uid;
  return jsonb_build_object('ok',true,'klass',jsonb_build_object('id',k.id,'namn',k.namn,'larare',k.larare));
end $function$;

-- ---------------------------------------------------------------------
-- Admin
CREATE OR REPLACE FUNCTION public.kg_admin_klasser()
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO ''
AS $function$
begin
  if auth.uid() is null then raise exception 'kg:ej_inloggad'; end if;
  if not public.kg_ar_admin() then raise exception 'kg:ej_admin'; end if;
  return jsonb_build_object(
    'klasser', coalesce((
      select jsonb_agg(jsonb_build_object(
        'id',k.id,'namn',k.namn,'ordning',k.ordning,'larare',k.larare,
        'elever', coalesce((
          select jsonb_agg(jsonb_build_object(
            'user_id',m.user_id,
            'namn',coalesce(nullif(s.data->>'namn',''), split_part(u.email,'@',1)),
            'epost',u.email,
            'xp',coalesce((s.data->>'xp')::bigint,0),
            'satt',m.satt) order by lower(coalesce(nullif(s.data->>'namn',''), u.email)))
            from kg_private.klassmedlem m
            left join kg_private.state s on s.id = m.user_id
            left join auth.users u on u.id = m.user_id
           where m.klass_id = k.id), '[]'::jsonb)
      ) order by k.ordning, lower(k.namn))
      from public.kg_klass k), '[]'::jsonb),
    'utan_klass', coalesce((
      select jsonb_agg(jsonb_build_object(
        'user_id',s.id,
        'namn',coalesce(nullif(s.data->>'namn',''), split_part(u.email,'@',1)),
        'epost',u.email,
        'xp',coalesce((s.data->>'xp')::bigint,0)) order by lower(coalesce(nullif(s.data->>'namn',''), u.email)))
        from kg_private.state s
        left join auth.users u on u.id = s.id
       where not exists (select 1 from kg_private.klassmedlem m where m.user_id = s.id)), '[]'::jsonb)
  );
end $function$;

CREATE OR REPLACE FUNCTION public.kg_admin_klass_spara(p_id bigint, p_namn text, p_ordning integer DEFAULT 0)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare v_id bigint;
begin
  if auth.uid() is null then raise exception 'kg:ej_inloggad'; end if;
  if not public.kg_ar_admin() then raise exception 'kg:ej_admin'; end if;
  if p_namn is null or char_length(btrim(p_namn)) not between 1 and 40 then
    return jsonb_build_object('ok',false,'code','namn');
  end if;
  begin
    if p_id is null then
      insert into public.kg_klass(namn,ordning) values(btrim(p_namn),coalesce(p_ordning,0)) returning id into v_id;
    else
      update public.kg_klass set namn = btrim(p_namn), ordning = coalesce(p_ordning,ordning) where id = p_id returning id into v_id;
      if v_id is null then return jsonb_build_object('ok',false,'code','okand_klass'); end if;
    end if;
  exception when unique_violation then
    return jsonb_build_object('ok',false,'code','namn_upptaget');
  end;
  return jsonb_build_object('ok',true,'id',v_id);
end $function$;

CREATE OR REPLACE FUNCTION public.kg_admin_klass_ta_bort(p_id bigint)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
begin
  if auth.uid() is null then raise exception 'kg:ej_inloggad'; end if;
  if not public.kg_ar_admin() then raise exception 'kg:ej_admin'; end if;
  if exists (select 1 from public.kg_klass where id = p_id and larare) then
    return jsonb_build_object('ok',false,'code','lararklass');
  end if;
  delete from public.kg_klass where id = p_id;     -- medlemskapen försvinner via on delete cascade
  return jsonb_build_object('ok',found);
end $function$;

CREATE OR REPLACE FUNCTION public.kg_admin_satt_klass(p_user uuid, p_klass bigint)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
begin
  if auth.uid() is null then raise exception 'kg:ej_inloggad'; end if;
  if not public.kg_ar_admin() then raise exception 'kg:ej_admin'; end if;
  if p_klass is null then
    delete from kg_private.klassmedlem where user_id = p_user;
    return jsonb_build_object('ok',true);
  end if;
  if not exists (select 1 from public.kg_klass where id = p_klass) then
    return jsonb_build_object('ok',false,'code','okand_klass');
  end if;
  insert into kg_private.klassmedlem(user_id,klass_id,satt,satt_av) values(p_user,p_klass,now(),auth.uid())
    on conflict (user_id) do update set klass_id = excluded.klass_id, satt = now(), satt_av = auth.uid();
  return jsonb_build_object('ok',true);
end $function$;

-- ---------------------------------------------------------------------
-- Topplistor
CREATE OR REPLACE FUNCTION public.topplista_klasser(p_period text DEFAULT 'vecka')
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare v_start timestamptz; v_tak bigint; v_rader jsonb;
begin
  if p_period not in ('dag','vecka','manad','alla') then
    raise exception 'Ogiltig period' using errcode='22023';
  end if;
  v_start := kg_private.klass_start(p_period);
  v_tak := kg_private.klass_tak(p_period);
  with medlem as (
    select m.klass_id, p.xp, p.uppgifter
      from kg_private.klassmedlem m
      join kg_private.state s on s.id = m.user_id and s.review_required = false
      cross join lateral kg_private.klass_period(m.user_id, v_start) p
  ),
  per_klass as (
    select k.id, k.namn, k.larare,
           count(md.klass_id)::int as elever,
           count(md.klass_id) filter (where md.uppgifter > 0)::int as aktiva,
           coalesce(sum(md.xp),0)::bigint as xp,
           coalesce(round(avg(least(md.xp, v_tak))),0)::bigint as poang
      from public.kg_klass k
      left join medlem md on md.klass_id = k.id
     group by k.id, k.namn, k.larare
  ),
  rankad as (
    select *, row_number() over (order by poang desc, aktiva desc, lower(namn)) as plats
      from per_klass where elever > 0
  )
  select coalesce(jsonb_agg(jsonb_build_object(
           'id',id,'namn',namn,'larare',larare,'elever',elever,'aktiva',aktiva,
           'xp',xp,'poang',poang,'plats',plats) order by plats), '[]'::jsonb)
    into v_rader from rankad;
  return jsonb_build_object(
    'rader', v_rader,
    'tak', v_tak,
    'min_klass', (select m.klass_id from kg_private.klassmedlem m where m.user_id = auth.uid())
  );
end $function$;

CREATE OR REPLACE FUNCTION public.topplista_klass_elever(p_klass bigint, p_period text DEFAULT 'vecka')
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare v_start timestamptz; v_rader jsonb;
begin
  if p_period not in ('dag','vecka','manad','alla') then
    raise exception 'Ogiltig period' using errcode='22023';
  end if;
  v_start := kg_private.klass_start(p_period);
  -- Bara elever som själva valt att synas på topplistan visas med namn.
  select coalesce(jsonb_agg(jsonb_build_object('namn',x.namn,'xp',x.xp,'uppgifter',x.uppgifter,'niva',x.niva,'rang',x.rang)
                            order by x.xp desc, x.uppgifter desc, lower(x.namn)), '[]'::jsonb)
    into v_rader
    from (
      select t.namn, t.niva, t.rang, p.xp, p.uppgifter
        from kg_private.klassmedlem m
        join kg_private.state s on s.id = m.user_id and s.review_required = false
        join public.topplista t on t.id = m.user_id and t.visa = true
        cross join lateral kg_private.klass_period(m.user_id, v_start) p
       where m.klass_id = p_klass
    ) x;
  return jsonb_build_object('rader', v_rader);
end $function$;

-- ---------------------------------------------------------------------
-- Behörigheter: funktionerna ska kunna anropas via API:t.
grant execute on function public.kg_klasser() to anon, authenticated;
grant execute on function public.topplista_klasser(text) to anon, authenticated;
grant execute on function public.topplista_klass_elever(bigint, text) to anon, authenticated;
grant execute on function public.kg_min_klass() to authenticated;
grant execute on function public.kg_valj_klass(bigint) to authenticated;
grant execute on function public.kg_admin_klasser() to authenticated;
grant execute on function public.kg_admin_klass_spara(bigint, text, integer) to authenticated;
grant execute on function public.kg_admin_klass_ta_bort(bigint) to authenticated;
grant execute on function public.kg_admin_satt_klass(uuid, bigint) to authenticated;

commit;
